services:
  - type: web
    name: bedorme-bot
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python bedorme.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: COMPLETED_ORDERS_CHANNEL_ID
        sync: false
      - key: CREATOR_BOT_TOKEN
        sync: false
      - key: CREATOR_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.6

  - type: web
    name: bedorme-creator
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python creator_bot.py
    envVars:
      - key: CREATOR_BOT_TOKEN
        sync: false
      - key: CREATOR_ID
        sync: false
      - key: CREATOR_PING_URL
        value: https://bedorme-creator.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.6
