services:
  - type: worker
    name: bedorme-bot
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python bedorme.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: COMPLETED_ORDERS_CHANNEL_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.6
